// src/@speechly/react-ui/components/Callout.tsx
import React from 'react'
import styled from 'styled-components'
import { animated, useSpring } from 'react-spring'

const CalloutContainerDiv = styled(animated.div)<{ax: string, ay: string, halign: string, valign: string, arrowpad: string}>`
  position: absolute;
  left: ${props => `${props.ax}`};
  top: ${props => `${props.ay}`};
  transform: ${props => `translate(calc(-1 * ${props.halign}), calc(-1 * ${props.valign}));`};
  padding: ${props => `${props.arrowpad}`};
  z-index: 10;
  pointer-events: auto;
`

const CalloutDiv = styled.div<{useShadow: boolean, backgroundColor: string, borderRadius?: string}>`
  position: relative;
  box-sizing: border-box;
  min-width: 8rem;
  ${props => props.borderRadius !== undefined && `border-radius: ${props.borderRadius}`};
  padding: 0.75rem 1rem;
  ${props => `background-color: ${props.backgroundColor}`};
  ${props => props.useShadow && 'box-shadow: 0 0.2rem 0.5rem #00000040'};
  text-align: center;
  user-select: none;
  color:#fff;
  z-index: 10;
`

const ArrowDiv = styled.div<{size: string, backgroundColor: string, ax: string, ay: string, offsetX: string, offsetY: string}>`
  position: absolute;
  left: ${props => `calc(${props.ax} - ${props.offsetX})`};
  top: ${props => `calc(${props.ay} - ${props.offsetY})`};

  transform: translate(-50%, -50%) rotate(45deg);
  width: ${props => `${props.size}`};
  height: ${props => `${props.size}`};
  ${props => `background-color: ${props.backgroundColor}`};
  z-index: 10;
`

const ArrowShadowDiv = styled.div<{size: string, ax: string, ay: string, offsetX: string, offsetY: string}>`
  position: absolute;
  left: ${props => `calc(${props.ax} - ${props.offsetX})`};
  top: ${props => `calc(${props.ay} - ${props.offsetY})`};

  transform: translate(-50%, -50%) rotate(45deg);
  width: ${props => `${props.size}`};
  height: ${props => `${props.size}`};
  background-color: #00000000;
  box-shadow: 0 0.2rem 0.5rem #00000040;
  z-index: 9;
`

type AnchorProps = {
  x: string
  y: string
}

type CssDimension = {
  value: number
  unit: string
}

type CalloutProps = {
  visible?: boolean
  onClick?: () => void
  sourceAnchors?: AnchorProps
  destAnchors?: AnchorProps
  arrowSize?: CssDimension
  useShadow?: boolean
  backgroundColor?: string
  borderRadius?: string
}

export const Callout: React.FC<CalloutProps> = ({
  children,
  onClick = () => {},
  sourceAnchors = { x: '50%', y: '5%' },
  destAnchors = { x: '50%', y: '100%' },
  visible = true,
  arrowSize = { value: 0.5, unit: 'rem' },
  useShadow = false,
  backgroundColor = '#000',
  borderRadius,
}) => {
  const springProps = useSpring({
    v: visible ? 1 : 0,
    config: { tension: 200 },
  })

  return (
    <CalloutContainerDiv ax={sourceAnchors.x} ay={sourceAnchors.y} halign={destAnchors.x} valign={destAnchors.y} arrowpad={`${arrowSize.value}${arrowSize.unit}`} onClick={() => onClick()} style={{
      visibility: springProps.v.interpolate(x => x as number > 0 ? 'visible' : 'hidden'),
      clipPath: springProps.v.interpolate(x => `circle(${x as number * 100}% at center)`),
    }}>
      <CalloutDiv useShadow={useShadow} backgroundColor={backgroundColor} borderRadius={borderRadius}>{children}</CalloutDiv>
      <ArrowDiv backgroundColor={backgroundColor} size={`${arrowSize.value * Math.sqrt(2)}${arrowSize.unit}`} ax="50%" ay="100%" offsetX="0rem" offsetY={`${arrowSize.value}${arrowSize.unit}`}/>
      {useShadow && <ArrowShadowDiv size={`${arrowSize.value * Math.sqrt(2)}${arrowSize.unit}`} ax="50%" ay="100%" offsetX="0rem" offsetY={`${arrowSize.value}${arrowSize.unit}`}/>}
    </CalloutContainerDiv>
  )
}

// libraries/browser-ui/src/call-out.svelte
<svelte:options tag={null} immutable={true} />

<script lang="ts">
  import fix from './fixTransition'

  const INSTRUCTION_PREROLL_MS = 500

  export let show = undefined;
  export let showtime = 10000;
  export let backgroundcolor = "#202020";

  let sourceAnchors = { x: '50%', y: '10%' };
  let destAnchors = { x: '50%', y: '100%' };
  let arrowSize = { value: 0.55, unit: 'rem' };
  let useShadow = false;
  let borderRadius = "0rem";
  let timeout = null;
  let showCallout = false;

  // Preroll and auto-hide logic
  $: scheduleShow(show) 

  const circlewipe = fix((node, { duration = 250 }) => {
    return {
      duration,
      css: (t: number) => {
        return `
          clip-path: circle(${t * 100}% at center);
        `
      }
    }
  });

  const scheduleShow = (show) => {
    if (timeout !== null) {
      window.clearTimeout(timeout);
      timeout = null;
    }

    if (show !== undefined && show !== "false") {
      timeout = window.setTimeout(() => {
        showCallout = true;
        timeout = null;
        if ((showtime as unknown as number) > 0) {
          timeout = window.setTimeout(() => {
            showCallout = false;
            timeout = null;
          }, (showtime as unknown as number));
        }
      }, INSTRUCTION_PREROLL_MS);
    } else {
      showCallout = false;
    }
  }

  const onMouseDown = (event) => {
    event.preventDefault();
    event.stopPropagation();
    showCallout = false;
  }

</script>

<main style="
  --ax: {sourceAnchors.x};
  --ay: {sourceAnchors.y};
  --halign: {destAnchors.x};
  --valign: {destAnchors.y};
  --borderradius: {borderRadius};
  --arrowpad: {`${arrowSize.value}${arrowSize.unit}`};
  --backgroundcolor: {backgroundcolor};
  --size: {`${arrowSize.value * Math.sqrt(2)}${arrowSize.unit}`};
  --offsetx: {"0rem"};
  --offsety: {`${arrowSize.value}${arrowSize.unit}`};
">
  {#if showCallout}
    <div class="CalloutContainerDiv"
      on:mousedown={onMouseDown}
      on:touchstart={onMouseDown}
      on:dragstart={onMouseDown}
      in:circlewipe
      out:circlewipe
    >
      <div class="CalloutDiv" class:useShadow={useShadow}><slot></slot></div>
      <div class="ArrowDiv" style="
        --ax: 50%;
        --ay: 100%;
      "/>
      {#if useShadow}
        <div class="ArrowShadowDiv"/>
      {/if}
    </div>
  {/if}
</main>

<style>
  main {
    margin:0;
    padding:0;
  }

  .CalloutContainerDiv {
    position: absolute;
    left: var(--ax);
    top: var(--ay);
    transform: translate(calc(-1 * var(--halign)), calc(-1 * var(--valign)));
    padding: var(--arrowpad);
    z-index: 10;
    pointer-events: auto;
  }

  .CalloutDiv {
    position: relative;
    box-sizing: border-box;
    min-width: 8rem;
    border-radius: var(--borderradius);
    padding: 0.50rem 1rem;
    background-color: var(--backgroundcolor);
    text-align: center;
    user-select: none;
    z-index: 10;
  }

  .useShadow {
    box-shadow: 0 0.2rem 0.5rem #00000040;
  }

  .ArrowDiv {
    position: absolute;
    left: calc(var(--ax) - var(--offsetx));
    top: calc(var(--ay) - var(--offsety));

    transform: translate(-50%, -50%) rotate(45deg);
    width: var(--size);
    height: var(--size);
    background-color: var(--backgroundcolor);
    z-index: 10;
  }

  .ArrowShadowDiv {
    position: absolute;
    left: calc(var(--ax) - var(--offsetx));
    top: calc(var(--ay) - var(--offsety));

    transform: translate(-50%, -50%) rotate(45deg);
    width: var(--size);
    height: var(--size);
    background-color: var(--backgroundcolor);
    background-color: #00000000;
    box-shadow: 0 0.2rem 0.5rem #00000040;
    z-index: 9;
  }

</style>
