// libraries/react-ui/src/components/PushToTalkButton.tsx
import React, { useEffect, useRef, useState } from 'react'
import { ClientState, useSpeechContext } from '@speechly/react-client'
import PubSub from 'pubsub-js'
import { SpeechlyUiEvents } from '../types'
import { PushToTalkButtonContainer } from '..'
import styled from 'styled-components'

declare global {
  // eslint-disable-next-line @typescript-eslint/no-namespace
  namespace JSX {
    interface IntrinsicElements {
      'holdable-button': any
    }
    interface IntrinsicElements {
      'call-out': any
    }
  }
}

/**
 * Properties for PushToTalkButton component.
 *
 * @public
 */
export type PushToTalkButtonProps = {
  /**
   * Optional "bottom" string turns on internal placement without any CSS positioning.
   */
  placement?: string

  /**
   * Keyboard key to use for controlling the button.
   * Passing e.g. ` ` (a spacebar) will mean that holding down the spacebar key will key the button pressed.
   */
  captureKey?: string

  /**
   * The size of the button, as CSS (e.g. `5rem`).
   */
  size?: string

  /**
   * Colours of the gradient around the button.
   * Valid input is an array of two hex colour codes, e.g. `['#fff', '#000']`.
   */
  gradientStops?: string[]

  /**
   * Optional boolean. Default: false
   */
  hide?: boolean

  /**
   * Optional string containing a short usage introduction. Displayed when the component is first displayed. Default: "Push to talk". Set to "" to disable.
   */
  intro?: string

  /**
   * Optional string containing a short usage hint. Displayed on a short tap. Default: "Push to talk". Set to "" to disable.
   */
  hint?: string

  /**
   * Optional CSS string for hint text. Default: "1.2rem"
   */
  fontSize?: string

  /**
   * Optional number in ms. Visibility duration for intro and hint callouts. Default: "5000" (ms)
   */
  showTime?: number

  /**
   * Optional string (CSS color) for hint text. Default: "#ffffff"
   */
  textColor?: string

  /**
   * Optional string (CSS color) for hint text background. Default: "#202020"
   */
  backgroundColor?: string

  /**
   * Optional boolean. Shows poweron state. If false, recording can immediately start but will first press will cause a system permission prompt. Default: false
   */
  powerOn?: boolean

  /**
   * Optional CSS string. Vertical distance from viewport edge. Only effective when using placement.
   */
  voffset?: string

  /**
   * Optional time in milliseconds to listen after tap. Set to 0 to disable tap-to-talk. Default: "8000" (ms)
   */
  tapToTalkTime?: number

  /**
   * Optional milliseconds of silence to listen before hangup. Only used in tap-to-talk mode. Default: "1000" (ms)
   */
  silenceToHangupTime?: number

}

/**
 * A React component that renders a push-to-talk microphone button.
 *
 * Make sure to place this component inside your `SpeechProvider` component imported from `@speechly/react-client`.
 *
 * @public
 */

type IButtonState = {
  tapListenActive: boolean
  wasListening: boolean
  holdListenActive: boolean
  tapListenTimeout: number | null
  tangentPressPromise: Promise<void> | null
}

export const PushToTalkButton: React.FC<PushToTalkButtonProps> = ({
  powerOn = false,
  hide = false,
  captureKey,
  size,
  gradientStops = ['#15e8b5', '#4fa1f9'],
  intro = 'Hold to talk',
  hint = 'Hold to talk',
  fontSize = '100%',
  showTime,
  textColor = '#ffffff',
  backgroundColor,
  placement,
  voffset,
  tapToTalkTime = 8000,
  silenceToHangupTime = 1000,
}) => {
  const { client, clientState, initialize, startContext, stopContext, segment } = useSpeechContext()
  const [loaded, setLoaded] = useState(false)
  const [icon, setIcon] = useState<string>((powerOn ? ClientState.Disconnected : ClientState.Connected) as unknown as string)
  const [hintText, setHintText] = useState<string>(intro)
  const [showHint, setShowHint] = useState(true)
  const buttonStateRef = useRef<IButtonState>({
    tapListenActive: false,
    wasListening: false,
    holdListenActive: false,
    tapListenTimeout: null,
    tangentPressPromise: null,
  })
  const buttonRef = useRef<any>()
  const clientStateRef = useRef<ClientState>()

  const TAP_TRESHOLD_MS = 600
  const PERMISSION_PRE_GRANTED_TRESHOLD_MS = 1500

  // make stateRef always have the current count
  // your "fixed" callbacks can refer to this object whenever
  // they need the current value.  Note: the callbacks will not
  // be reactive - they will not re-run the instant state changes,
  // but they *will* see the current value whenever they do run
  clientStateRef.current = clientState

  // Dynamic import of HTML custom element to play nice with Next.js SSR
  useEffect(() => {
    // eslint-disable-next-line @typescript-eslint/no-floating-promises
    (async () => {
      const import1 = import('@speechly/browser-ui/core/holdable-button')
      const import2 = import('@speechly/browser-ui/core/call-out')
      await Promise.all([import1, import2])
      setLoaded(true)
    })()
  }, [])

  useEffect(() => {
    // eslint-disable-next-line @typescript-eslint/strict-boolean-expressions
    if (buttonRef?.current) {
      const button = buttonRef.current
      button.onholdstart = tangentPressAction
      button.onholdend = tangentReleaseAction
    }
  })

  useEffect(() => {
    // Change button face according to Speechly states
    if (!powerOn && clientState === ClientState.Disconnected) {
      setIcon(ClientState.Connected as unknown as string)
    } else {
      setIcon(clientState as unknown as string)
    }

  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [clientState])

  const tangentPressAction = async (): Promise<void> => {
    buttonStateRef.current.tangentPressPromise = (async() => {
      PubSub.publish(SpeechlyUiEvents.TangentPress, { state: clientStateRef.current })
      window.postMessage({ type: 'holdstart', state: clientStateRef.current }, '*')
      setShowHint(false)

      if (buttonStateRef.current.tapListenTimeout) {
        window.clearTimeout(buttonStateRef.current.tapListenTimeout)
        buttonStateRef.current.tapListenTimeout = null
      }

      switch (clientStateRef.current) {
        case ClientState.Disconnected:
          // Speechly & Mic initialise needs to be in a function triggered by event handler
          // otherwise it won't work reliably on Safari iOS as of 11/2020
          const initStartTime = Date.now()
          try {
            await initialize()
          } catch (err) {
            console.error('Error initiasing Speechly', err)
          }
          // await buttonStateRef.current.initPromise
          // Long init time suggests permission dialog --> prevent listening start
          buttonStateRef.current.holdListenActive = !powerOn && Date.now() - initStartTime < PERMISSION_PRE_GRANTED_TRESHOLD_MS
          break
        default:
          buttonStateRef.current.holdListenActive = true
          break
      }

      // Start listening
      if (buttonStateRef.current.holdListenActive) {
        buttonStateRef.current.wasListening = client.isListening()
        if (!client.isListening()) {
          try {
            await startContext()
          } catch (err) {
            console.error('Error while starting to record', err)
          }
        }
      }
    })()
  }

  const tangentReleaseAction = async (event: any): Promise<void> => {
    // Ensure async tangentPress and Release are run in appropriate order
    await buttonStateRef.current.tangentPressPromise

    PubSub.publish(SpeechlyUiEvents.TangentRelease, { state: clientStateRef.current, timeMs: event.timeMs })
    window.postMessage({ type: 'holdend' }, '*')

    if (buttonStateRef.current.holdListenActive) {
      buttonStateRef.current.holdListenActive = false

      if (event.timeMs < TAP_TRESHOLD_MS) {
        if (tapToTalkTime === 0) {
          setHintText(hint)
          setShowHint(true)
        } else {
          // Tap: toggle listening on/off
          if (buttonStateRef.current.wasListening) {
            stopListening()
          } else {
            // schedule "silence based stop"
            setStopContextTimeout(tapToTalkTime)
          }
        }
      } else {
        stopListening()
      }
    }
  }

  const setStopContextTimeout = (timeoutMs: number): void => {
    buttonStateRef.current.tapListenActive = true
    if (buttonStateRef.current.tapListenTimeout) {
      window.clearTimeout(buttonStateRef.current.tapListenTimeout)
    }
    buttonStateRef.current.tapListenTimeout = window.setTimeout(() => {
      buttonStateRef.current.tapListenTimeout = null
      stopListening()
    }, timeoutMs)
  }

  const stopListening = (): void => {
    buttonStateRef.current.tapListenActive = false
    if (client.isListening()) {
      try {
        // eslint-disable-next-line @typescript-eslint/no-floating-promises
        stopContext()
      } catch (err) {
        console.error('Error while stopping recording', err)
      }
    }
  }

  /**
   * Extend listening time if segment updates received
   */
  useEffect(() => {
    if (segment) {
      if (buttonStateRef.current.tapListenTimeout) {
        setStopContextTimeout(silenceToHangupTime)
      }
    }
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [segment])

  if (!loaded) return null

  return (
    <MicButtonDiv textColor={textColor} fontSize={fontSize}>
      { (placement === 'bottom') && (
        <PushToTalkButtonContainer size={size} voffset={voffset}>
          <holdable-button ref={buttonRef} poweron={powerOn} capturekey={captureKey} icon={icon} size={size} gradientstop1={gradientStops[0]} gradientstop2={gradientStops[1]} hide={hide ? 'true' : 'false'}></holdable-button>
          <call-out show={showHint && hintText !== ''} backgroundcolor={backgroundColor} showtime={showTime}>{hintText}</call-out>
        </PushToTalkButtonContainer>
      )}
      { (placement !== 'bottom') && (
        <>
          <holdable-button ref={buttonRef} poweron={powerOn} capturekey={captureKey} icon={icon} size={size} gradientstop1={gradientStops[0]} gradientstop2={gradientStops[1]} hide={hide ? 'true' : 'false'}></holdable-button>
          <call-out show={showHint && hintText !== ''} backgroundcolor={backgroundColor} showtime={showTime}>{hintText}</call-out>
        </>
      )}
    </MicButtonDiv>
  )
}

const MicButtonDiv = styled.div<{textColor: string, fontSize: string}>`
  font-family: 'Saira Condensed', sans-serif;
  color: ${(props) => props.textColor};
  font-size: ${(props) => props.fontSize};
  line-height: 120%;
  text-transform: uppercase;
`

// libraries/browser-ui/src/push-to-talk-button.svelte
<svelte:options tag={null} immutable={true} />

<script lang="ts">
  import "./holdable-button.ts";
  import "./call-out.ts";
  import { Client, ClientState, Segment } from "@speechly/browser-client";
  import { onMount } from "svelte";
  import { createDispatchUnbounded} from "./fixDispatch";
  import { IHoldEvent, LocalStorageKeys, MessageType } from "./types";

  const TAP_TRESHOLD_MS = 600
  const PERMISSION_PRE_GRANTED_TRESHOLD_MS = 1500
  const dispatchUnbounded = createDispatchUnbounded();

  export let projectid: string = undefined;
  export let appid: string = undefined;
  export let loginurl = undefined;
  export let apiurl = undefined;

  export let capturekey = " ";
  export let poweron = undefined;
  export let hide = undefined;
  export let taptotalktime = 8000; // ms to listen after tap. Set to 0 to disable tap-to-talk.
  export let silencetohanguptime = 1000; // ms of silence to listen before hangup

  export let intro = "Hold to talk";
  export let hint = "Hold to talk";
  export let showtime = 10000;

  export let placement = undefined;
  export let size = "80px";
  export let voffset = "2.5rem";

  export let backgroundcolor = "#ffffff";
  export let iconcolor = "#000000";
  export let gradientstop1 = "#15e8b5";
  export let gradientstop2 = "#4fa1f9";

  export let fontsize = "1.2rem";
  export let textcolor = "#ffffff";
  export let hintbackgroundcolor = "#202020";

  export let holdscale = "1.35";
  export let borderscale = "0.075";
  export let iconsize = "60%";
  export let fxsize = "250%";
  export let cssimport = undefined;
  export let customtypo = undefined;

  let useFTUEPermissionPriming = false;
  let icon: ClientState = ClientState.Disconnected;
  let holdListenActive = false;
  let initializedSuccessfully = undefined;
  let tipCalloutVisible = false;
  let mounted = false;

  let tapListenTimeout = null;
  let tapListenActive = false;
  let tangentStartPromise = null;

  $: tipCallOutText = intro;
  $: showPowerOn = poweron !== undefined && poweron !== "false";
  $: icon = showPowerOn ? ClientState.Disconnected : ClientState.Connected;
  $: connect(projectid, appid);
  $: defaultTypography = customtypo === undefined || customtypo === "false";

  let client = null;
  let clientState: ClientState = undefined;

  onMount(() => {
    mounted = true;
    useFTUEPermissionPriming = (document.querySelector("intro-popup") !== null) && (localStorage.getItem(LocalStorageKeys.SpeechlyFirstConnect) === null);
    connect(projectid, appid);
  });

  const connect = (projectid: string, appid: string) => {
    if (mounted && !client && (projectid || appid)) {
      const clientOptions = {
        ...(appid && !projectid && {appId: appid}),
        ...(projectid && {projectId: projectid}),
        ...(loginurl && {loginUrl: loginurl}),
        ...(apiurl && {apiUrl: apiurl}),
      }
      client = new Client(clientOptions);

      client.onStateChange(onStateChange);
      client.onSegmentChange((segment: Segment) => {
        // Refresh stopContext timeout if set
        if (tapListenTimeout) setStopContextTimeout(silencetohanguptime);
        // Pass on segment updates from Speechly API as events
        dispatchUnbounded(MessageType.speechsegment, segment);
        // And as window.postMessages
        window.postMessage({ type: MessageType.speechsegment, segment: segment }, "*");
      });

      // Temporary check for client.connect function
      if (typeof client.connect === "function") {
        client.connect();
      }

      tipCalloutVisible = true;
    }
  }

  const initialize = async () => {
    // Initialize the client - this will ask the user for microphone permissions and establish the connection to Speechly API.
    // Make sure you call `initialize` from a user action handler (e.g. from a button press handler).

    try {
      dispatchUnbounded("starting");
      window.postMessage({
        type: MessageType.speechlystarting
      }, "*");
      await client.initialize();
    } catch (e) {
      console.error("Speechly initialization failed", e);
      client = null;
    }
  };

  const tangentStart = async (event) => {
    tangentStartPromise = (async () => {
      tipCalloutVisible = false;
      if (client) {
        // Connect on 1st press
        if (useFTUEPermissionPriming) {
          window.postMessage({
            type: MessageType.speechlyrequestpriming
          }, "*");
        } else if (isConnectable(clientState)) {
          if (appid || projectid) {
            const initStartTime = Date.now();
            await initialize();
            // Long init time suggests permission dialog --> prevent listening start
            holdListenActive = !showPowerOn && Date.now() - initStartTime < PERMISSION_PRE_GRANTED_TRESHOLD_MS;
          } else {
            console.warn(
              "No appid/projectid attribute specified. Speechly voice services are unavailable."
            );
          }
        } else {
          holdListenActive = true;
        }

        if (holdListenActive) {
          if (tapListenTimeout) {
            window.clearTimeout(tapListenTimeout);
            tapListenTimeout = null;
          }
          if (isStartable(clientState)) {
            dispatchUnbounded("startcontext");
            client.startContext(appid);
          }
        }
      }
      // Send as window.postMessages
      window.postMessage({ type: MessageType.holdstart, state: clientState }, "*");
    })()
  };

  const tangentEnd = async (event) => {
    // Ensure async tangentStart and end are run in appropriate order
    await tangentStartPromise;

    if (client && holdListenActive) {
      holdListenActive = false;
      const holdEventData: IHoldEvent = event.detail;

      // Detect short press
      if (holdEventData.timeMs < TAP_TRESHOLD_MS) {
        if (taptotalktime == 0) {
          tipCallOutText = hint;
          tipCalloutVisible = true;
        } else {
          // Short press when not recording = schedule "silence based stop"
          if (!tapListenActive) {
            setStopContextTimeout(taptotalktime);
          }
        }
      }

      if (!tapListenTimeout) {
        stopListening();
      }
    }

    // Send as window.postMessages
    window.postMessage({ type: "holdend" }, "*");
  };

  const setStopContextTimeout = (timeoutMs: number) => {
    tapListenActive = true;
    if (tapListenTimeout) {
      window.clearTimeout(tapListenTimeout);
    }
    tapListenTimeout = window.setTimeout(() => {
      tapListenTimeout = null;
      stopListening();
    }, timeoutMs);
  }

  const stopListening = () => {
    tapListenActive = false;
    if (client) {
      if (isStoppable(clientState)) {
        client.stopContext();
        dispatchUnbounded("stopcontext");
      }
    }
    updateSkin();
  }

  const updateSkin = () => {
    if (clientState !== null) icon = clientState;
  };

  const isConnectable = (clientState?: ClientState) => {
    if (!clientState) return true;
    return clientState === ClientState.Disconnected;
  };

  const isStartable = (clientState: ClientState) =>
    clientState === ClientState.Connected;

  const isStoppable = (s: ClientState) => {
    switch (s) {
      case ClientState.Starting:
      case ClientState.Recording:
      // case ClientState.Stopping:
        return true;
      default:
        return false;
    }
  };

  const onStateChange = (s: ClientState) => {
    clientState = s;
    updateSkin();
    switch(s) {
      case ClientState.Failed:
      case ClientState.NoBrowserSupport:
      case ClientState.NoAudioConsent:
        setInitialized(false, s as unknown as string);
        break;
      case ClientState.Connected:
        setInitialized(true, s as unknown as string);
        // Automatically start recording if button held
        if (!showPowerOn && (holdListenActive || tapListenActive) && isStartable(clientState)) {
          dispatchUnbounded("startcontext");
          client.startContext(appid);
        }
        break;
    }
    // Broadcast state changes
    window.postMessage({ type: MessageType.speechstate, state: s }, "*");
  };

  const setInitialized = (success: boolean, state: string) => {
    if (initializedSuccessfully === undefined) {
      initializedSuccessfully = success;
      useFTUEPermissionPriming = false;
      if (localStorage.getItem(LocalStorageKeys.SpeechlyFirstConnect) === null) {
        localStorage.setItem(LocalStorageKeys.SpeechlyFirstConnect, String(Date.now()));
      }
      
      window.postMessage({
        type: MessageType.initialized,
        success: initializedSuccessfully,
        appId: appid,
        state
      }, "*");

      dispatchUnbounded(MessageType.initialized, {
        success: initializedSuccessfully,
        appId: appid,
        state
      });

    }
  }

  const handleMessage = (e) => {
    switch (e.data.type) {
      case MessageType.showhint:
        tipCallOutText = e.data.hint;
        tipCalloutVisible = true;
        break;
      case MessageType.speechlyintroready:
        useFTUEPermissionPriming = localStorage.getItem(LocalStorageKeys.SpeechlyFirstConnect) === null;
        break;
    }
  }

</script>

<svelte:window on:message={handleMessage}/>

<svelte:head>
  {#if defaultTypography}
    <link href="https://fonts.googleapis.com/css2?family=Saira+Condensed:wght@700&display=swap" rel="stylesheet">
  {/if}
</svelte:head>

<holdable-button class:placementBottom={placement === "bottom"}
  on:holdstart={tangentStart}
  on:holdend={tangentEnd}
  {size}
  {icon}
  {capturekey}
  {gradientstop1}
  {gradientstop2}
  {hide}

  {backgroundcolor}
  {iconcolor}
  {holdscale}
  {borderscale}
  {iconsize}
  {fxsize}
  {cssimport}

  style="
    --voffset: {voffset};
    --size: {size};
    --textcolor: {textcolor};
    --fontsize: {fontsize};
  ">
  <call-out class:defaultTypography={defaultTypography} show={tipCallOutText !== "" && tipCalloutVisible && !hide ? "true" : "false"} showtime={showtime} backgroundcolor={hintbackgroundcolor}>{tipCallOutText}</call-out>
</holdable-button>

<style>
  .placementBottom {
    position: fixed;
    bottom: 0;
    left: 0;
    right: 0;
    height: calc(var(--size) + var(--voffset));
    max-height: 100vh;
    pointer-events: none;

    display: flex;
    flex-direction: row;
    justify-content: center;
    z-index: 50;
  }

  call-out.defaultTypography {
    font-family: 'Saira Condensed', sans-serif;
    color: var(--textcolor);
    font-size: var(--fontsize);
    line-height: 120%;
    text-transform: uppercase;
  }

</style>
